### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by katcatalano** [amyko/pedigreeSA#1]
I'm having trouble running the program, is something not initialized that I need to initialize before running the program? Hope this isn't an obvious oversight on my end. Thanks!
![screen shot 2017-08-16 at 3 30 28 pm](https://user-images.githubusercontent.com/26149625/29382009-45d6b038-8299-11e7-9fd5-71efe13fff03.png)

**Comment by amyko** [comment]
Hi,

I think you might be running an old version of the program. Could you try
the program in github/amyko/clapper? The input is still the same. You can
try running the example files and see if it works.

Best,
Amy

**Comment by katcatalano** [comment]
Hi Amy,

Good catch! I'm using the new version now, and I have no problem running the test data, but I have the same error again. I've triple checked all of my data formats, any tips to figure out the source of the error?

Thanks!

**Comment by amyko** [comment]
I'm out of office today but I can take a look at it tomorrow.

In the meantime, I would check if all sites are polymorphic in the
reference data (i.e. minor allele frequency > 0) and remove any fixed
sites. Let me know if this helps at all.

Best,
Amy

**Comment by katcatalano** [comment]
Hi Amy,

Yes, all of my sites are polymorphic, fixed sites removed. I've tried again and have the same error. Would it be helpful to send you my data?

**Comment by amyko** [comment]
Yes, that would be helpful!
